### ISSUE TITLE
How do I annotate after loading the data 

### ISSUE THREAD

**Issue by EmmaGuo910** [microsoft/TagAnomaly#19] opened 2020-07-06 06:21 UTC
There is no button "Add selected points" on the web page to annotate an anomaly. How should I annotate?
![image](https://user-images.githubusercontent.com/67617633/86561715-e1f13300-bf93-11ea-8a22-22fbc4be6d5a.png)
![image](https://user-images.githubusercontent.com/67617633/86561755-ef0e2200-bf93-11ea-96da-a9809edc0ca5.png)

**Comment by omri374** [comment] 2020-07-06 08:24
Hi @EmmaGuo910, thanks for your issue. Are you using the Docker image on Dockerhub, or have cloned the repo and ran it locally?

**Comment by EmmaGuo910** [comment] 2020-07-07 01:51
> Hi @EmmaGuo910, thanks for your issue. Are you using the Docker image on Dockerhub, or have cloned the repo and ran it locally?

I ran it locally in RStudio

**Comment by omri374** [comment] 2020-07-07 07:50
Could you please verify you have this line in ui.R? 
https://github.com/microsoft/TagAnomaly/blob/0022f1666ab9efb2f7aa9eb1f52bcc007f5cb2d8/ui.R#L65

**Comment by EmmaGuo910** [comment] 2020-07-08 08:50
> Could you please verify you have this line in ui.R?
> https://github.com/microsoft/TagAnomaly/blob/0022f1666ab9efb2f7aa9eb1f52bcc007f5cb2d8/ui.R#L65

I verified there was that code
![image](https://user-images.githubusercontent.com/67617633/86898091-d68c3c00-c13a-11ea-9168-d87172104ed6.png)
![image](https://user-images.githubusercontent.com/67617633/86898126-e277fe00-c13a-11ea-8b2e-d227b80976ef.png)

**Comment by omri374** [comment] 2020-07-08 09:01
It seems like you are loading an old version... Could it be? For example, the line following `add` and `delete` says "Currently marked points" but on the screenshot it says "Selected points" (which was the old version. See PR #16)

I would try to do a fresh clone of the repo and try again.

**Comment by EmmaGuo910** [comment] 2020-07-09 07:47
> It seems like you are loading an old version... Could it be? For example, the line following `add` and `delete` says "Currently marked points" but on the screenshot it says "Selected points" (which was the old version. See PR #16)
> 
> I would try to do a fresh clone of the repo and try again.

Thanks. It worked after I switched branch to 1515e42f618d2c73bff116f6cabe63ef799e54c6.

However, I was confused by the issue followed.  I downloaded the labels set after added points to candidate list. The csv file showed that the category remains normal. (I see from documentation that I can merge several csv files afterwards). If that so, "Add selected points" is meaningless, I suppose, because I could just selected points in the graph and download. It will generate same result after merging csv files.
![image](https://user-images.githubusercontent.com/67617633/87011692-d81d3900-c1fa-11ea-9016-843dd3a17a7f.png)
![image](https://user-images.githubusercontent.com/67617633/87012179-81642f00-c1fb-11ea-84b9-465f1ee4b5b8.png)

**Comment by omri374** [comment] 2020-07-12 07:43
The new functionality allows you to select multiple locations on the graph and download them combined. If you have anomalies at the beginning of your time series, and at the end, you might need to perform multiple selections.

**Comment by EmmaGuo910** [comment] 2020-07-13 02:28
I understand. Thanks a lot.

**Comment by EmmaGuo910** [comment] 2020-07-13 02:28
I understand. Thanks a lot.

**Comment by EmmaGuo910** [comment] 2020-07-13 02:28
I understand. Thanks a lot.

**Comment by dean-sh** [comment] 2020-10-08 18:08
Hey @omri374,
I'm having the same issue, not being able to label the data after loading it.
I tried running master branch, or `1515e42` as you suggested, and also run the image from DockerHub.

I don't have the option to add the candidates to the desired category.

How can I add the labels?
![image](https://user-images.githubusercontent.com/26027302/95496839-b2423480-09a1-11eb-9977-eaefeb0ef28f.png)

**Comment by omri374** [comment] 2020-10-08 19:21
Hey @dean-sh, I'm not sure why this is happening. Could you too verify you have this line in ui.R? 
https://github.com/microsoft/TagAnomaly/blob/0022f1666ab9efb2f7aa9eb1f52bcc007f5cb2d8/ui.R#L65

**Comment by dean-sh** [comment] 2020-10-08 20:15
> Hey @dean-sh, I'm not sure why this is happening. Could you too verify you have this line in ui.R?
> https://github.com/microsoft/TagAnomaly/blob/0022f1666ab9efb2f7aa9eb1f52bcc007f5cb2d8/ui.R#L65

Indeed I do.

**Comment by omri374** [comment] 2020-12-14 07:48
I could not reproduce this on two different versions of R. If anybody has this issue, please provide reproduction steps (including OS, R version and shiny version)

**Comment by omri374** [comment] 2021-01-03 20:30
Found the root cause for this. There were two ui.R and server.R files on the repo. Fixed on #22

**Closed as completed by omri374** 2021-01-03 20:30 UTC
